using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;
using StockManagementSystem.Models;

namespace StockManagementSystem
{
    public partial class BillsClientView : Form
    {
        public BillsClientView()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            StockManagementSystem.Models.AppDBContext dbContext = new StockManagementSystem.Models.AppDBContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.CustomerBills.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.CustomerBills.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            //AppDBContext context = new AppDBContext();


            gridView1.OptionsView.ShowGroupPanel = false;

          
        }

        private void gridControl1_Load(object sender, EventArgs e)
        {

        }

        private async void BillsClientView_Load(object sender, EventArgs e)
        {
   
            var dbContext = new StockManagementSystem.Models.AppDBContext();

            await dbContext.CustomerBills
                .Include(cb => cb.Customer)
                .Include(cb => cb.Items)
                .LoadAsync();

            gridControl1.DataSource = dbContext.CustomerBills.Local.ToBindingList();
      

    }
}
}
