using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.EntityFrameworkCore;

namespace StockManagementSystem
{
    public partial class BillsClientView : Form
    {
        public BillsClientView()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            StockManagementSystem.Models.AppDBContext dbContext = new StockManagementSystem.Models.AppDBContext();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.CustomerBills.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.CustomerBills.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
